apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-vineela3
  namespace: vineela3
subjects:
- kind: ServiceAccount
  name: vineela-sa
  namespace: vineela3
roleRef:
  kind: Role 
  name: role-vineela3
  apiGroup: rbac.authorization.k8s.io
